#include "raylib.h"
#include "raymath.h"

constexpr int SCREEN_WIDTH = 1024;
constexpr int SCREEN_HEIGHT = 768;

constexpr int HORIZONTAL_TILES = 40;
constexpr int VERTICAL_TILES = 30;

constexpr float TILE_WIDTH = float(SCREEN_WIDTH) / float(HORIZONTAL_TILES);
constexpr float TILE_HEIGHT = float(SCREEN_HEIGHT) / float(VERTICAL_TILES);

constexpr int PLAYING_FIELD_HORIZONTAL_TILES = 24;
constexpr int PLAYING_FIELD_VERTICAL_TILES = 28;

constexpr int PLAYING_FIELD_OFFSET_HORIZONTAL_TILES = 2;
constexpr int PLAYING_FIELD_OFFSET_VERTICAL_TILES = 1;

constexpr Vector2 PLAYING_FIELD_TOP_LEFT{
	PLAYING_FIELD_OFFSET_HORIZONTAL_TILES * TILE_WIDTH,
	PLAYING_FIELD_OFFSET_VERTICAL_TILES * TILE_HEIGHT
};

constexpr Vector2 PLAYING_FIELD_BOTTOM_RIGHT{
	(PLAYING_FIELD_OFFSET_HORIZONTAL_TILES + PLAYING_FIELD_HORIZONTAL_TILES) * TILE_WIDTH,
	(PLAYING_FIELD_OFFSET_VERTICAL_TILES + PLAYING_FIELD_VERTICAL_TILES) * TILE_HEIGHT
};

constexpr Rectangle PLAYING_FIELD_RECT{
	PLAYING_FIELD_OFFSET_HORIZONTAL_TILES * TILE_WIDTH,
	PLAYING_FIELD_OFFSET_VERTICAL_TILES * TILE_HEIGHT,
	PLAYING_FIELD_HORIZONTAL_TILES * TILE_WIDTH,
	PLAYING_FIELD_VERTICAL_TILES * TILE_HEIGHT
};

constexpr Vector2 PLAYER_INITIAL_VECTOR{
	(PLAYING_FIELD_OFFSET_HORIZONTAL_TILES + PLAYING_FIELD_HORIZONTAL_TILES / 2) * TILE_WIDTH,
	(PLAYING_FIELD_OFFSET_VERTICAL_TILES + PLAYING_FIELD_VERTICAL_TILES - 2) * TILE_HEIGHT
};

constexpr float PLAYER_HITBOX_RADIUS = 4.f;

constexpr float PLAYER_HORIZONTAL_SPEED = 600.f;
constexpr float PLAYER_VERTICAL_SPEED = 400.f;

constexpr Vector2 PLAYER_SPEED_VECTOR{
	PLAYER_HORIZONTAL_SPEED,
	PLAYER_VERTICAL_SPEED
};
